@startuml
' STYLE START
hide empty members

skinparam shadowing false
<style>
document {
  BackgroundColor transparent
  Margin 0
}
</style>
' STYLE END

class BlockHitBlockEvent << (S, SkyBlue) struct >> { 
  ~controlBlockId : EntityID
  ~landedBlockId : EntityID 
}
@enduml