@startuml
' STYLE START
hide empty members

skinparam shadowing false
<style>
document {
  BackgroundColor transparent
  Margin 0
}
</style>
' STYLE END

class BlockComponent { 
  ~playerId : EntityID
  ~movingDirection : CGFloat
  ~useWidthForGuideline : Bool
}
@enduml