@startuml ButtonPressSequenceDiagram

actor User
participant Main.storyboard <<View>>
participant GameViewController <<Controller>>
participant BaseGameScene <<Game Loop>>
participant GameManager <<Model>>
participant EventManager
participant ButtonPressEvent <<Event>>
participant InputSystem <<System>>

== Firing event ==

User -> Main.storyboard: tap player 1's button
Main.storyboard -> GameViewController: buttonTapped()
GameViewController -> GameManager: handleButtonPress()
GameManager -> ButtonPressEvent: init()
GameManager -> EventManager: fire(ButtonPressEvent())

== Executing events ==

BaseGameScene -> GameManager: didFinishUpdate()
GameManager -> EventManager: pollAll()
EventManager -> ButtonPressEvent: execute()
ButtonPressEvent -> InputSystem: handleButtonPress()

@enduml
