@startuml ButtonDownSequenceDiagram

actor User
participant Main.storyboard <<View>>
participant GameViewController <<Controller>>
participant BaseGameScene <<Game Loop>>
participant GameManager <<Model>>
participant EventManager
participant ButtonDownEvent <<Event>>
participant AXInputSystem <<System>>

== Firing event ==

User -> Main.storyboard: tap player 1's button
Main.storyboard -> GameViewController: buttonPressed()
GameViewController -> GameManager: handleButtonDown()
GameManager -> ButtonDownEvent: init()
GameManager -> EventManager: fire(ButtonDownEvent())

== Executing events ==

BaseGameScene -> GameManager: didFinishUpdate()
GameManager -> EventManager: pollAll()
EventManager -> ButtonDownEvent: execute()
ButtonDownEvent -> AXInputSystem: handleButtonDown()

@enduml
