@startuml IndexMapInitializableClassDiagram
hide empty members

protocol IndexMapInitializable {
  [Int: EntityID] playerIndexToIdMap
  
  setPlayerId(firstPlayer: EntityID, secondPlayer: EntityID)
}
