@startuml
' STYLE START
hide empty members

skinparam shadowing false
<style>
document {
  BackgroundColor transparent
  Margin 0
}
</style>
' STYLE END

class SPGameManager << (C, DarkSeaGreen) >> extends GameManager { 
  ~setUpEntities()
  ~setUpUserSystems() 
}
class SPGameViewController << (C, DarkSeaGreen) >> extends GameViewController { 
  ~setUpGameManager()
  ~customiseBackgroundViewAndSound() 
}

protocol InputSystem {
  ~playerIndexToIdMap : [Int: EntityID]
  ~handleButtonDown(playerIndex:)
  ~handleButtonUp(playerIndex:)
}

class SPInputSystem << (C, DarkSeaGreen) >> implements InputSystem { 
  ~entityManager : EntityManager
}

@enduml