@startuml
' STYLE START
hide empty members

skinparam shadowing false
' STYLE END

class ResetRoundEvent << (S, SkyBlue) struct >>

class AXInputSystem {
  ~reset()
  ~handleButtonDown(playerIndex:)
  ~handleButtonUp(playerIndex:) 
}

class AXScoreSystem {
  ~handleAxeHitPlayer(withEntityId:)
}

class AXRoundSystem {
  ~reset()
}

@enduml